version: '3.8'

services:
  main-server:
    build: ./main-server
    container_name: main-server
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/exploreWithMe
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: iamroot
      TZ: "Europe/Moscow"

  db:
    image: postgres
    container_name: explore_With_Me
    ports:
      - "6432:5432"
    volumes:
      - /var/lib/postgresql/data/
    environment:
      POSTGRES_DB: exploreWithMe
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: iamroot

  stat-server:
    build: ./stat-server
    container_name: stat-server
    ports:
      - "9090:9090"
    depends_on:
      - db2
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5433/statistic
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: iamroot
      TZ: "Europe/Moscow"
    restart: always

  db2:
    image: postgres
    container_name: statistic
    ports:
      - "6433:5432"
    volumes:
      - /var/lib/postgresql/data/
    environment:
      POSTGRES_DB: statistic
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: iamroot

