version: '3.8'

services:
  main-server:
    build: ./main-server
    container_name: main_server
    ports:
      - "8080:8080"
    depends_on:
      - db_main
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/exploreWithMe
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: iamroot
      TZ: "Europe/Moscow"

  db_main:
    image: postgres:13.7-alpine
    container_name: db_main
    ports:
      - "6541:5432"
    volumes:
      - /var/lib/postgresql/data/
    environment:
      POSTGRES_DB: exploreWithMe
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: iamroot

  stat-server:
    build: ./stat-server
    container_name: stat_server
    ports:
      - "9090:9090"
    depends_on:
      - db_statistic
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/statistic
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: iamroot
      TZ: "Europe/Moscow"

  db_statistic:
    image: postgres:13.7-alpine
    container_name: db_statistic
    ports:
      - "6543:5432"
    volumes:
      - /var/lib/postgresql/data/
    environment:
      POSTGRES_DB: statistic
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: iamroot

