version: '3.1'

services:
  main-server:
    build: ./main-server
    container_name: main-server
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/exploreWithMe
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: iamroot
      TZ: "Europe/Moscow"
    restart: always

  db:
    image: postgres:13.7-alpine
    container_name: explore_With_Me
    ports:
      - "6432:5432"
    volumes:
      - /var/lib/postgresql/data/
    environment:
      POSTGRES_DB: exploreWithMe
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: iamroot

#  stat-server:
#
#  stats-db:
#    image: postgres:14-alpine
#
#  ewm-service:
#    ports:
#      - "9090:9090"
#
#  ewm-db:
#    image: postgres:14-alpine
